### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by l123456789jy**
Modify the maven dependency error report,
Could not set unknown property'url' for repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

### CODE REVIEW

**Comment by Jadarma** [comment]
The current version is correct, since it is written for Gradle with Kotlin DSL (notice the kotlin marker for the markdown code block).
The fix you submitted is for a Groovy script. It would not be a valid `build.gradle.kts` file.

**Comment by l123456789jy** [comment]
> The current version is correct, since it is written for Gradle with Kotlin DSL (notice the kotlin marker for the markdown code block).
> The fix you submitted is for a Groovy script. It would not be a valid `build.gradle.kts` file.

But there is no place to indicate that it is KotlinKotlin DSL, it will be misunderstood early, should it be indicated?

**Comment by nuhkoca** [comment]
It would be better if you implement collapsable blocks for Groovy and make Kotlin DSL expanded by default. You can refer to my [PR](https://github.com/JLLeitschuh/ktlint-gradle/pull/305 ) for [ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle) repository to see how it better fits.

**Comment by ilya-g** [comment]
Thanks for the PR, but we now the library artifacts can be found in `mavenCentral()`, which looks the same in Kotlin and in Groovy scripts, see https://github.com/Kotlin/kotlinx-datetime/blob/d3c63fb/README.md#gradle

**Pull request closed without merging**
