### PR TITLE
Update gradle wrapper and specify distribution sha256

### PR DESCRIPTION
**Pull request by ilya-g**
The result of executing `gradlew wrapper` command with the current Gradle version.
I've also checked that the wrapper.jar checksum matches the official one for 7.5.1: https://gradle.org/release-checksums/

### CODE REVIEW

**Comment by dkhalanskyjb** [comment]
Did you manage to find out when the checksum could be useful for us? I only found this explanation: https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification If I understood correctly, we would need to enable a GitHub action in order for this to have at least some purpose.

**Comment by ilya-g** [comment]
distributionSha256Sum in gradle-wrapper.properties is verified by the wrapper itself each time it downloads Gradle distribution, for example when building on a freshly started agent.
The integrity of the wrapper itself can be verified by setting up a github action.

**Comment by dkhalanskyjb** [comment]
What's the point though? It's already transferred over https, so no one is going to be able to swap the distribution unless
* Gradle's servers are compromised, or
* Someone hacks the DNS record for the gradle server.

**Comment by ilya-g** [comment]
Won't hurt anyway

**Comment by dkhalanskyjb** [comment]
Sure, my point is, maybe we could also enable the GitHub Acton so that this line pulls its weight?

**Comment by ilya-g** [comment]
Continued in #259

**Pull request closed without merging**
