### PR TITLE
Fix Instant parsing on Native being too lenient

### PR DESCRIPTION
**Pull request by dkhalanskyjb**

### CODE REVIEW

**Comment by ilya-g** [comment]
First we need to discuss what behavior we want from `Instant.parse`. In java.time, for example, Instant.parse does support times like 23:59:60.

**Comment by dkhalanskyjb** [comment]
Closing in favor of #251

**Comment by ilya-g** [comment]
I believe we still should discuss how to address an inconsistency between platforms if there is any.

**Comment by ilya-g** [comment]
There's no inconsistency between platforms in kotlinx.datetime, but there's inconsistency between kotlinx.datetime and java.time in `Instant.parse`. Let's reopen.

**Comment by dkhalanskyjb** [comment]
Ok: #332

**Pull request closed without merging**
