### PR TITLE
Update Dokka to 1.8.10

### PR DESCRIPTION
**Pull request by IgnatBeresnev**
[Changelog](https://github.com/Kotlin/dokka/releases/tag/v1.8.10)

Cannot build and check it locally, I have some problems with kotlin/native dependencies or something :( Should hopefully be OK

### CODE REVIEW

**Comment by dkhalanskyjb** [comment]
Did you try this https://github.com/Kotlin/kotlinx-datetime#building?

**Comment by IgnatBeresnev** [comment]
> Did you try this https://github.com/Kotlin/kotlinx-datetime#building?

Indeed, that was it! Much easier than I anticipated, sorry I didn't research it myself :sweat_smile: 

Ran Dokka 1.8.10 locally, everything looks OK

**Review by dkhalanskyjb — APPROVED** [review]

**Review by ilya-g — APPROVED** [review]

**Comment by IgnatBeresnev** [comment]
At the moments it's unclear which branch such changes should be targeting (master/develop), so I'll take until the end of the week to clarify with Vsevolod, and come back

Will merge the PR once everyone agrees on the process

**Comment by IgnatBeresnev** [comment]
@ilya-g oh, didn't even notice, thanks!

**Pull request merged**
